add_newline = true
command_timeout = 200
format = "$directory$git_branch$git_status$character"

[character]
success_symbol = "[›](bold white)"
error_symbol = "[›](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold blue"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style) "
format = "[$path]($style) "

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = "yellow"
ahead = "↑"
behind = "↓"
diverged = "↕"
conflicted = "!"
untracked = "?"
modified = "•"
staged = "+"
stashed = ""
renamed = ""
deleted = ""
up_to_date = ""
